### ISSUE TITLE
Issue installing swarm-contrastive-decomposition: jpca not found

### ISSUE THREAD

**Issue by haripen** [AgneGris/swarm-contrastive-decomposition#2]
Hi Agnese,

Thank you for the effort you put into making the decomposition code available!

Unfortunately, I encountered an issue while attempting to install the ``swarm-contrastive-decomposition`` repository from your provided ``decomposition.yml`` file. Unfortunately, the installation failed on two separate PCs and on my Mac laptop with the same error message.
Here are some details of my environment and the error:
 - Environment: decomp_agne (originally named decomposition)
 - Python Version: 3.10.13 (Anaconda environment)
 - Numpy Version: 1.2.34
 - Torch Version: 2.1.1
 - Scipy: 1.13.1
 - Matplotlib: 3.5.3

Error Message:
````
Installing pip dependencies: / Ran pip subprocess with arguments:
['C:\\ProgramData\\anaconda3\\envs\\decomp_agne\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\User\\Downloads\\swarm-contrastive-decomposition\\condaenv.4w5i1k2s.requirements.txt']
Pip subprocess output:
Collecting easydict==1.13 (from -r C:\Users\User\Downloads\swarm-contrastive-decomposition\condaenv.4w5i1k2s.requirements.txt)
  Downloading easydict-1.13-py3-none-any.whl.metadata (4.2 kB)
Collecting h5py==3.10.0 (from -r C:\Users\User\Downloads\swarm-contrastive-decomposition\condaenv.4w5i1k2s.requirements.txt)
  Downloading h5py-3.10.0-cp310-cp310-win_amd64.whl.metadata (2.5 kB)
Collecting hdmf==3.11.0 (from -r C:\Users\User\Downloads\swarm-contrastive-decomposition\condaenv.4w5i1k2s.requirements.txt)
  Downloading hdmf-3.11.0-py3-none-any.whl.metadata (8.8 kB)

Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement jpca==0.0.1 (from versions: none)
ERROR: No matching distribution found for jpca==0.0.1

failed

CondaEnvException: Pip failed
````

It seems there is an issue finding a compatible version for ``jpca==0.0.1``. I would appreciate any guidance or solutions you might have to resolve this issue.

Thank you in advance for your help.

Best regards,
Harald

**Comment by AgneGris** [comment]
Hi Harald,

Thank you for trying the code and for flagging this issue. 

I have just removed the jpca from the required dependencies in the decomposition.yml since it is not needed. Let me know if you are able to install it now.

Best,
Agnese

P.S. Love the environment name!

**Comment by haripen** [comment]
Hi Agnese!

Thanks for the quick fix, the installation went through this time. I'll try the decomposition soon!

Best,
Harald
